### ISSUE TITLE
make timeout for long running errors in deployers configurable

### ISSUE THREAD

**Issue by reshnm** [gardener/landscaper#318]
**How to categorize this issue?**

/area deployers
/kind enhancement
/priority 4

**What would you like to be added**:

Currently the timeout for long running errors in deployers is fixed to 5 minutes:

https://github.com/gardener/landscaper/blob/master/pkg/deployer/lib/error.go#L32

Make this value configurable.

**Why is this needed**:

In some cases, the target on which the deployer operates, may not be ready within 5 minutes.
It would be helpful for the user to specify a custom timeout value for long running errors and keep the 5 minutes as a default.

**Comment by Diaphteiros** [comment]
Hm, not sure I get the point of this issue.
We currently have a `ProgressingTimeout` which specifies how long the deployer may take to process the deploy item before being aborted. This timeout is configurable per deploy item, so users can increase the duration for long-running deploy items.

The timeout mentioned by you is how long the landscapers waits when an error occurs before it actually reports this error. Increasing this duration will lead to an increased timespan in which the deploy item is stuck in `Progressing` without showing the reason for it. 

It would probably be better to prevent the error from occurring instead of telling the landscaper that it is allowed to ignore the error for a longer amount of time, if that's possible ...
Do you have a concrete scenario in mind for which a longer error timeout duration would be helpful?

**Comment by reshnm** [comment]
The problem in my scenario is, that the deploy item is using a target that was created be a previous installation.
It may be the case that this target is not ready for quite some time.
Everything is working fine when the target becomes ready in <= 5 minutes. If it not becomes ready, the deployment will fail.
I know, this scenario is kind of a niche and only applies for when depending on a newly created kubernetes cluster target, however we might run into more of these issues when deploying gardener landscapes.

We could also argue, that the one creating the target has to make sure, once it is exported, it has to be "ready".
However, I'm not sure how to enforce such a requirement.
Therefore I think it would be helpful to make this one configurable.

**Comment by Diaphteiros** [comment]
What do you mean with the target being 'ready'? A target is a simple custom resource, either it exists or it doesn't exist, but I don't see how it could exist but not be 'ready' - am I missing something here?

**Comment by reshnm** [comment]
It is not about the target resource state being ready.
It is about the kubernetes cluster the target resource is pointing to being ready.
The target resource can exist and being used without the cluster being ready, which leads to errors like this:

`Get "https://10.0.0.1:443/api?timeout=32s": dial tcp 10.0.0.1:443: connect: connection refused`

If the cluster is ready before 5 minutes have passed, the deployment using this target will succeed.
If the cluster is not ready within 5 minutes the deployment will fail.

**Comment by achimweigel** [comment]
@In-Ko closed because outdated and/or copied into internal project
